env:
  global:
  - REPO_TAG_NAME=$TRAVIS_TAG
  - secure: scPwS5t6PA3exGhcaTTfYJFh5p3EEhwM0zKSl8/OW2jsyuppg0z9JXwvZKHH4MDr8cjbOAs9DKCnAt06AO+9qraWuur9fM0NY/wXe3FyWeVFxPPmU6hRHNw+5RizyGGr18AFox1Jd8pIdJEObLmwzADeGbRbB15z4oej7fd5TQcKH6ZBRX+CWMEZToCyuVWs0dIxd6UOCAo0MiNJefXjV58cxhe7I1yxYq/Iewg0xhiLHfKA50thQKGDsD4PO9g3aBzcMN64mDSRhKuRwkIxHrZQom1myFXv4J6UR1VaHoElfK4F7FD9r3hEv0CDz++tsrHOCVKrrSX8+ohGx0ey9LmkxIVp1nOFxGzoWEPx5bdmRJ0o2ayF4C1yVpXhERh90FwTi5zfkod+TKvuFU5BFD+AyPFQtAuY0tEC5yZnIisbT6CvQT4+Soo6rXTYPGrh9hp39W5vRBVzoeTEiafJGw5tJUxJU/1d6j20KTTUaeu6yym70WA4YBK9X4o6yOvaAcpwV1Z2ywE6IDqh4kGkiKTI6dIeo2VQ5z98xMvSjhetsRN8aN4vgjc6A8XJOsf/Grbz3CXs3KC5CZrcTcP7NLB98c5mWcZhrbWXjVLSohTiNXGJwPEuVH5Mftqnywss0QbpsF/e0V0j+R104PzahH9VUSTLoR/iB4l3h9H0hNc=
  - secure: sZyk58nHQBweXNtSaPKp/DxdBzX+sBMoI5IhOgkrMRC51YZ5ZWrABJBl1Q8ZIT+wfXmDs3pA2VlqMZibjTYo9MGAY72VitsnNldy19QKEKCvbCU1QGiGDqzpkpOhLm/2jcX4mBdcNaZWueUZnXcqICmCpwA6HhSk6ElmzjkYycrf94KLNxQvoO/XbWXCu08ev5bNRYJjo6pgpilFcwSW/+VRifLxxOnLDrbwah4i6z4GApTm8HJxoFG+ky8i3e/GrxQF/Ykn8tRV8II6RpA2+vEYXbTvFuQbGyrx97B5B8ia7jGMdmsnNNdCibdDdYWGljjLWVj0sXouZfhfPf0tBgFusvdhipuqPqqOFvRo1sRQUym2ZALBwzZASRRn6yR2sP9tGJsRm/R7rFjNiMBuhjwHvMbXcmRW5J+Bt22Gwf02MMClIbAQg5gG5odp6tqxIr0a6Uol657qbDp79CQ1ajXblGbgSR6Zh0x/32G1CvHsK0xKIOZ/+NeryQu5uGBsEnGGGKDFP3FsVjesvY/XE721Uwzda0/EXDDLKOcQVfS8e4tiPsSu+JconKGZ2B0qS5C5R7diyBwy1/QjkZ2/PHvQQ1OX2pfVYTCmqZcXuW3hJxGw8LYJi2q8kfbkBdfcjpMsg44viJUXh1pzBuJQcDY+mKTAdOBqcwLiTJqf864=
  - secure: YezIL2Fqccvi1Ov0fhwvrVn+KnlA6BrX1/IxM0On0TQ5EHZ653grPwmmI4qY5jGQVLiIK01VbHRFIRcz8z6w2ap1ShVng937W+aqrWicB9o7TlqUbJzjByPcBSRlg074oumqYiE2KTILit2JfczfPmIQ1Y9R9DcWqU4u6FtfExByT0oZ6ttR0o+Dyp0jOSzSwOzpAuuTV+I8g0yon/hGIyzSh85KQ/9rOFqi3xWSIolCy6hEbGVmSlPlPChJGxrDqY0dwMScvWooY7Q/yTCDqOqCSK0OrSe7PAbNEiCunM5mpD/G9OQVSqBfUyFLXMsNXOvHXsAOh/IGLBWcgIn0pPtW6XmhDJbtb1wIcDnK//LzgwGdjcmUUyG40Mrk1iTDD0DQpKu5/INGEb30K0l7EC3RpKZmvFf4bIkQr3NPOeJh4+Ty18HbPDordivuunoIJSzKByVr9VbgUrdKLKC6VtrAdyfqDuIs036GHhU4AssQAoRu8E6SOKT+WvoxENFF4kNI13I3M8/VItNIWjAk3YmPN7D2lRZ2S3Bnga0Up0dFfT2hlkjHgeLp9J5JH3sMPGW1li8r5Gpb+E/3VyqPD0BDJ2MHHHbJyFiyDmKHRanlfvporO43f/1eAQHY20tHttCSFZKSG1IuVffgJhSEgdPAUxi1dXEm05rn2+x03ac=
  - secure: oAtYM/JoBgFe6u481fNJ2oeUXIzqo27+SNxlq4/Mm5RV4bmLrv8vA5/h6URTPvvHfSLZTSuhut0Rz9Z0auIfIHwvAnz1780hCoOjOi99PzmG72tLyydkzIQaek6zOowxaMEe8198a+GQznaHcuwISWzNZCcjGr2m65u2DwAozgwGfH+CgtKrT+3t9PLcBNLv6XUb0bzlHJ3JWB3Z5aIHGEBmi0G13tLTuTlnOXDjrQ0tm2n/dJLBq+hBXalSSyHcplqLMWXfQsh4e8Zs9PnQqXiNVaFTAKGhPDvo1wrfo9my8MhJWOVM/Yjo9KUhtOTiV2+rHO1FtN4tJoGQ/iv6GrYjyWKMbXzKj3CYb5KtQi9aDaE0iunIvjjJjw9BEsd4JpxySu3M1+vwZUf4NqNJRi7RW2RafEsdQcECyIMUhsZTLim41QRSH74bo44cDYrM7EQLuJgmNdCtyXWJl/zfBBpkrk4M6ORqbZGeye0bEWy54qLNxE4xXSpyJQo0Ow0YKiHxkwDhq4iQWOshI6BGGxgJgHSLsv/7xxC4Gerh5N5MVtDuGqGmRr0FhOd/jWbJ6YdcG4Xvc4/M3jSYeJBgxKLVssGitbs8W7FtVg2iryRDcB6hwgCMd/CSNbjsqGFinYS6ECxI4dlmPx/1eExSKIHiPf0GuVXzJ7/W7qNyhOA=
  - secure: h+xk8LRNFdf89XSGfz5D74N18Zpu1CPSBNH/LJ3mY5plwIhGIfsEW6K4PRc8XJnFxhUyaan9nPkMnAdg68CUjQRLWantjCj+CSmjyTMVed3WrkJhmt//znad/KWlnP6DHGbf/mYYCajB4QZZLx/6w2XpgOZWQE3j+hIigiOJRExLovy81BFvH1Ie18zVwwbzNaXr1/CdeMq18nBNEiGKRRxrhcVr3OmucEswEWtJci8CexMzchEq0cjGcQriU9xxCqe6ld791j5oWCyFoTNZYSXHD9rSvomn7rm1446Tr7M8jQKUzrPUwRvxggpgW73R/znCPoqm67JCP1pgg0x3TpZGDanBGep51hqWF8V5pK9SpjGnhQnCKP7VU0fV8RRSnzRdtinoYnv1OvUDjx49OV18fRnbs+ZKadfuWvog6eMU4UBSf/DhND+qt0r9bWzvJmNq7zGCNLcBcVnoYYc3tabee76qoi8h2CuScokZKGnW9xIN3BiDO+CjOCmgUZTL0yg44P7fvm7y9f2RdiyOZUKUqj7HRuPd6QFT73sCIpMbaBepfZnJrahW79epkQ368SowoviD5dB2YmVtRLJOA1p/T8UIWOnTfNyxag0LSua8+tZbFfb0P8P4kUy/1/+PbpJAKPD+3qUN6MkzZYWkabKlrwqrIXj3Sl6GUPxcB5o=
os:
- linux
branches:
  only:
  - master
  - "/^v.*$/"
language: java
install: true
jdk: openjdk8
script:
- if [ $TRAVIS_TAG == $TRAVIS_BRANCH ]; then export IS_TAG=true; else export IS_TAG=false;
  fi
- chmod +x gradlew
- gpg --fast-import ./distribution/publishing/codesigning.asc
- "./gradlew publishArtifacts assemble"
deploy:
  tag_name: "$TRAVIS_TAG"
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file:
  - build/distributions/*.zip
  skip_cleanup: true
  on:
    tags: true
